# -- 主菜单 --
# 主菜单显示在页面顶部的页眉中。
# 可接受的参数有 name、pageRef、page、url、title、weight。
#
# 最简单的菜单配置方式是提供：
#   name = 此菜单链接显示的名称
#   pageRef = 要链接的页面或版块的标识符
#
# 默认情况下菜单按字母顺序排列。可以通过提供 weight 值来覆盖，
# 菜单将按 weight 从低到高排序。
[[main]]
 name = "关于"
 pageRef = "index"
 weight = 5

[[main]]
 name = "文章"
 pageRef = "posts"
 weight = 10

 [[main]]
 name = "标签"
 pageRef = "tags"
 weight = 30

 [[main]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/COOKIE3319"
  weight = 40

# [[subnavigation]]
#  name = "一个有趣的话题"
#  pageRef = "tags/interesting-topic"
#  weight = 10

# [[subnavigation]]
#  name = "我的精彩分类"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20





# -- 页脚菜单 --
# 页脚菜单显示在页面底部，紧接在版权声明之前。
# 配置方式与上面的主菜单相同。


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
