# -- 主题选项 --
# 这些选项控制主题的功能，并允许你自定义网站的显示方式。
#
# 有关每个参数的更多详细信息，请参阅主题文档。
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish" #主题使用的颜色方案。合法的值有： blowfish （默认）、avocado、fire、ocean、forest、princess、neon、bloody、terminal、marvel、noir、autumn、congo 和 slate。 具体参考颜色方案以获取更多信息。
defaultAppearance = "light" # 有效选项: light 或 dark
autoSwitchAppearance = true #主题外观是否根据访问者操作系统的偏好自动切换。设置为 false 会强制网站始终使用 defaultAppearance。

enableSearch = true #是否开启网站的搜索功能，设为 true 即为启用。注意，搜索功能依赖于站点设置中的 outputs.home 设置，请确保此值配置正确。
enableCodeCopy = true #是否可以将<code>代码块复制到剪贴板。想要使用代码复制功能，需要将 highlight.noClasses 参数设置为 false。 阅读 其他配置文件 以获取更多信息。

replyByEmail = false #是否在发布后启用“通过邮件回复”的链接。如果使用，则必须设置 config/_default/languages.en.toml 中的 params.author.email 参数。

mainSections = ["文章"] #指定最近文章中应该展示的模块。 如果没有指定，则使用文章数量最多的板块。
# robots = ""

disableImageOptimization = false #禁用图片上所有图片的调整大小和优化功能，使用 Markdown 语法插入的图片（![](image.jpg)）除外。
disableImageOptimizationMD = false #所有以 Markdown 语法（![](image.jpg)）插入的图片，禁用其调整大小和优化功能。
disableTextInHeader = false #禁用文本类型的标题，对基于 logo 的标题很有用。
# backgroundImageWidth = 1200 #宽度（以像素为单位）用于缩放背景图像。

defaultBackgroundImage = "/img/background.svg" #设置默认背景图，用于 background 和 hero 布局下的主页。
defaultFeaturedImage = "/img/featured.svg" #设置默认背景图片，用于所有文章的featured图片，可以通过文章目录中的 featured 图片替换。
defaultSocialImage = "/img/blowfish_banner.png" #社交媒体分享（Open Graph 和 Twitter）使用的默认图片，可以通过文章目录中的 featured 图片替换。

highlightCurrentMenuArea = true #当菜单被选择时，标记主菜单中的菜单项。
smartTOC = true #开启智能目录，视图中的项目将会被高亮显示。
smartTOCHideUnfocusedChildren = false #当开启智能目录，如果目录级别不再被聚焦时，将会隐藏更深层次的目录。

#giteaDefaultServer = "https://git.fsfe.org" #短代码 gitea 的默认 server 参数。
#forgejoDefaultServer = "https://v11.next.forgejo.org" #短代码 forgejo 的默认 server 参数。

fingerprintAlgorithm = "sha512" # 有效值为 "sha512"（默认）、"sha384"、"sha256"

[header]
  layout = "fixed" # 定义整个站点的页头的布局，支持的参数有 basic、fixed、fixed-fill、and fixed-fill-blur.

[footer]
  showMenu = true #显示/隐藏页面底部菜单，该菜单可以在 config/_default/menus.en.toml 文件中的 [[footer]] 部分进行配置。
  showCopyright = true #是否在底部显示 copyright 版权信息。请注意，如果你想定制，可以在语言配置中使用 copyright 参数。
  showThemeAttribution = true #是否在网站底部中显示"powered by" 的主题归属信息。如果禁用此参数，请考虑在你网站的其他位置设置主题归属信息，例如在关于页面。
  showAppearanceSwitcher = true #是否在也页面底部显示外观切换器。浏览器的本地存储会缓存访问者的偏好设置。
  showScrollToTop = true #当设置为 true 时，显示返回顶部的箭头按钮。

[homepage]
  layout = "custom" # 首页布局参数。合法的参数值有： page、profile、hero、card、background 或 custom。当你设置为 custom 时，你必须创建 /layouts/partials/home/custom.html 文件以定制自己的布局。参考主页布局来获取更多信息。
  homepage.homepageImage = "/img/background.svg" #在 hero 和 card 布局中使用的图像。图片可以来自于本地的资源目录，也可以是外部图像 URL。参考 主页布局 来获取更多信息。
  showRecent = true #是否在主页展示最新文章列表。
  showRecentItems = 0 #如果将 showRecent 设置为 true，此参数用于显示多少篇文章。如果没有设置或者为0，则默认显示5篇文章。
  showMoreLink = false #是否在主页底部添加“显示更多”，该链接会降会用带到一个预定义位置。
  showMoreLinkDest = "docs" #更多按钮所指向的位置。
  cardView = true #将列表展示为卡片容器。
  cardViewScreenWidth = false #增强列表中卡片的宽度，使其可以占据可用的全部宽度。
  layoutBackgroundBlur = true # 仅在 layout 等于 background 时使用,向下滚动主页时，是否模糊背景图。
  disableHeroImageFilter = false # 仅在 layout 等于 hero 时使用,主页背景是否套用图片滤镜。

[article]
  showDate = false #是否在文章中显示发布日期。
  showViews = false #是否在文章中显示浏览次数。
  showLikes = false #是否在文章中显示点赞次数。
  showDateOnlyInArticle = false #是否在文章内显示日期，不影响文章列表或卡片页面的日期显示。
  showDateUpdated = false #是否在文章中显示最后更新时间。
  showAuthor = false #是否在文章中显示作者信息。
  # showAuthorBottom = false #作者框显示在每页的底部而不是顶部。
  showHero = false #缩略图是否会在每个页面中作为 hero 图像显示。
  heroStyle = "background" # hero 图像的展示样式，可选的参数值有：basic、big、background、thumbAndBackground。
  layoutBackgroundBlur = true # 向下滚动文章页时，是否模糊背景图。
  layoutBackgroundHeaderSpace = true # 	在标题和正文之间添加空白区域间隔。
  showBreadcrumbs = true #是否在文章中显示面包屑导航。
  showDraftLabel = true #当使用 --buildDrafts 构建网站时，是否在文章旁边显示草稿。
  showEdit = false #是否在文章中显示编辑链接。
  #editURL = #当激活 article.showEdit 参数，此参数用于设置文章的编辑链接。
  editAppendPath = true #当激活 article.showEdit 参数，是否将文章的路径附加到 article.editURL 参数所设置的 URL 后面。
  seriesOpened = false #是否默认显示打开系列模块、
  showHeadingAnchors = false #是否在文章标题旁边显示锚点链接。
  showPagination = true #是否在文章末尾展示上一篇/下一篇的文章链接。
  invertPagination = false #是否翻转下一篇/上一篇文章链接的方向。
  showReadingTime = true #是否展示文章的阅读时间。如果你的语言包含 CJK 语言，需要在 config.toml 中开启 hasCJKLanguage 参数。
  showTableOfContents = true #是否展示文章的目录。
  showRelatedContent = true #为文章显示相关内容。如果你想要启用此功能，请检查 config.toml 文件并复制所有 related 相关的参数，如果你想自定义，也可以对 config.toml 添加额外配置。更多内容请参考 Hugo 文档 中关于 related 的内容。
  relatedContentLimit = 3 #如果启用showRelatedContent，则限制显示相关文章的数量。
  showTaxonomies = true #是否显示文章的分类或标签信息。
  showAuthorsBadges = true #是否在文章或列表中显示 authors 分类。这需要开启多个作者 multiple authors 和 authors 分类法。 请阅读 这个网页 来获取更多内容。
  showWordCount = false #是否显示文章的字数。 如果你的语言属于 CJK 语言，需要在 config.toml 中开启 hasCJKLanguage 参数。
  sharingLinks = [ "twitter", "telegram", "email"] #在文章末尾显示的分享链接。如果没有提供或设置为 false，则不会显示任何分享链接。可用的值包括：“bluesky”、“email”、“facebook”、“line”、“linkedin”、“mastodon”、“pinterest”、“reddit”、“telegram”、“twitter"和"whatsapp”
  showZenMode = false #指定是否激活文章阅读的禅模式，即隐藏常规的界面元素。

[list]
  showHero = true
  heroStyle = "background" # 有效选项: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # 仅在 heroStyle 等于 background 时使用
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  showCards = true
  orderByWeight = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background" # 有效选项: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  cardView = false

[term]
  showHero = true
  heroStyle = "background" # 有效选项: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  
[firebase]
  #apiKey = "AIzaSyB5tqlqDky77Vb4Tc4apiHV4hRZI18KGiY"
  #authDomain = "blowfish-21fff.firebaseapp.com"
  #projectId = "blowfish-21fff"
  #storageBucket = "blowfish-21fff.appspot.com"
  #messagingSenderId = "60108104191"
  #appId = "1:60108104191:web:039842ebe1370698b487ca"
  #measurementId = "G-PEDMYR1V0K"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[umamiAnalytics]
  # websiteid = "ABC12345"
  # domain = "llama.yoursite.com"
  # dataDomains = "yoursite.com,yoursite2.com"
  # scriptName = ""
  # enableTrackEvent = false

[selineAnalytics]
  # token = "XXXXXX"
  # enableTrackEvent = false


[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

[rssnext]
  # feedId = ""
  # userId = ""

[advertisement]
  # adsense = ""
